### ISSUE TITLE
ModuleNotFoundError

### ISSUE THREAD

**Issue by rodion-m** [Blaizzy/mlx-embeddings#4]
```
python3.10/site-packages/mlx_embeddings/utils.py", line 16, in <module>
    from huggingface_hub.utils._errors import RepositoryNotFoundError
ModuleNotFoundError: No module named 'huggingface_hub.utils._errors'
```

It's not good to import private classes.

**Comment by Blaizzy** [comment]
Thanks for flagging it! 

This was fixed yesterday here #3

**Comment by jpcompartir** [comment]
Hi thanks for the package, 

I was having the same issue on a fresh install. Steps to reproduce:

1. Fresh virtual environment
2. Installed via: `uv pip install mlx_embeddings`
3. The error persists in `.venv/lib/python3.*/site-packages/mlx_embeddings/utils.py` with:

I nipped into the package install change the import as above and looks good now, but does a new version need to be distributed?

**Comment by swlee60** [comment]
> Hi thanks for the package,
> 
> I was having the same issue on a fresh install. Steps to reproduce:
> 
> 1. Fresh virtual environment
> 2. Installed via: `uv pip install mlx_embeddings`
> 3. The error persists in `.venv/lib/python3.*/site-packages/mlx_embeddings/utils.py`
> 
> I nipped into the package install to change the import as above, and looks good now, but does a new version need to be distributed?

try this:
```
pip install git+https://github.com/Blaizzy/mlx-embeddings.git 
```
